---
# =========================================================
# Jenkins (cicd)
# - 단일 노드에서 안정적으로 동작하도록 hostPath PV + PVC 사용
# - 외부 노출은 Ingress로만 (Service는 ClusterIP)
# - 50000(JNLP agent) 포트는 일단 닫음(공격 표면 축소)
# =========================================================

# -----------------------------------------
# (1) PersistentVolume (단일 노드용 hostPath)
# - Jenkins 데이터(/var/jenkins_home)를 노드 디스크에 영구 저장
# - 멀티노드/실무 확장 시: EBS CSI/PVC(StorageClass)로 교체 권장
# -----------------------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-home-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-hostpath
  hostPath:
    #   노드(EC2) 로컬 경로
    # - 권장: /data/nyd/ 아래로 통일해서 인프라 데이터와 같이 관리
    path: /home/ubuntu/jenkins_home
    type: DirectoryOrCreate

---
# -----------------------------------------
# (2) PersistentVolumeClaim
# - 위 PV에 바인딩되도록 storageClassName을 동일하게 맞춤
# -----------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-pvc
  namespace: cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: jenkins-hostpath

---
# -----------------------------------------
# (3) Deployment
# - Jenkins 본체
# - serviceAccountName: jenkins (RBAC로 kubectl/helm 배포 권한 부여)
# -----------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins

      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk17
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080
            #   agent(50000) 포트는 일단 닫음
            # - K8s 에이전트(Pod Template) 방식으로 가면 보통 외부 노출 불필요
            # - 필요해지면 나중에 내부 전용으로만 추가

          env:
            - name: TZ
              value: "Asia/Seoul"

          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home

          #   단일 노드에서 컨트롤플레인 자원 고갈 방지
          resources:
            requests:
              cpu: "200m"
              memory: "1Gi"
            limits:
              cpu: "1500m"
              memory: "2Gi"

          #   헬스체크
          # - Jenkins는 초기 부팅이 느릴 수 있어서 initialDelay를 넉넉히 잡음
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12

          livenessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6

          #   보안 옵션(과하게 잠그면 플러그인/동작에 영향이 있을 수 있어 기본선만)
          securityContext:
            allowPrivilegeEscalation: false

      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home-pvc

---
# -----------------------------------------
# (4) Service (ClusterIP)
# - 외부 노출은 Ingress에서 처리
# - NodePort를 열지 않으니 보안그룹/방화벽도 단순해짐
# -----------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: cicd
spec:
  type: ClusterIP
  selector:
    app: jenkins
  ports:
    - name: http
      port: 8080
      targetPort: 8080
